import { NextRequest, NextResponse } from "next/server";
import { adminAuth, adminDb } from "@/lib/firebaseAdmin";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function POST(req: NextRequest) {
  try {
    if (!adminAuth || !adminDb) {
      return NextResponse.json({ error: "Firebase Admin SDK not initialized." }, { status: 500 });
    }

    const authHeader = req.headers.get("Authorization");
    if (!authHeader || !authHeader.startsWith("Bearer ")) {
      return NextResponse.json({ error: "Unauthorized. Missing Bearer token." }, { status: 401 });
    }

    const idToken = authHeader.split("Bearer ")[1];
    
    // Verify token
    let decodedToken;
    try {
      decodedToken = await adminAuth.verifyIdToken(idToken);
    } catch (err: any) {
      console.error("Token verification failed:", err);
      return NextResponse.json({ error: `Unauthorized. Invalid token: ${err.message}` }, { status: 401 });
    }

    const callerUid = decodedToken.uid;
    const callerEmail = decodedToken.email;

    // Check caller role
    const callerDoc = await adminDb.collection("users").doc(callerUid).get();
    if (!callerDoc.exists) {
      return NextResponse.json({ error: "Unauthorized. Caller not found in database." }, { status: 403 });
    }

    const callerData = callerDoc.data();
    const allowedRoles = ["owner_admin", "partner_admin", "developer_admin", "admin"];
    
    if (!callerData || !allowedRoles.includes(callerData.role)) {
      return NextResponse.json({ error: "Forbidden. Insufficient privileges to create staff." }, { status: 403 });
    }

    const body = await req.json();
    const { name, email, phone, password, permissions, status } = body;

    if (!email || !password || !name) {
      return NextResponse.json({ error: "Missing required fields (email, password, name)." }, { status: 400 });
    }

    if (password.length < 8) {
      return NextResponse.json({ error: "Password must be at least 8 characters long." }, { status: 400 });
    }

    // 1. Create user in Firebase Auth
    const userRecord = await adminAuth.createUser({
      email,
      password,
      displayName: name,
      ...(phone ? { phoneNumber: phone } : {})
    });

    // 2. Create user document in Firestore
    const userDocData = {
      role: "staff", // Force role to be "staff"
      status: status || "active",
      permissions: permissions || [],
      name,
      email,
      phone: phone || "",
      mustChangePassword: true, // Flag for future feature where they change password on first login
      createdAt: new Date().toISOString(),
      createdBy: callerUid
    };

    await adminDb.collection("users").doc(userRecord.uid).set(userDocData);

    // 3. Write Audit Log
    const logData = {
      actorUid: callerUid,
      actorName: callerData.name || callerEmail || "Unknown Admin",
      actorEmail: callerEmail || "Unknown",
      actorRole: callerData.role,
      action: "create_staff",
      section: "staff",
      documentChanged: userRecord.uid,
      newValue: `Created staff account for ${email} with permissions: ${(permissions || []).join(', ')}`,
      createdAt: new Date().toISOString()
    };
    
    // Add document to auditLogs collection. Random ID is generated by add() or setting a new doc reference.
    const logRef = adminDb.collection("auditLogs").doc();
    await logRef.set({
      ...logData,
      id: logRef.id
    });

    return NextResponse.json({ success: true, uid: userRecord.uid, message: "Staff created successfully." }, { status: 201 });
  } catch (error: any) {
    console.error("Error creating staff:", error);
    // If the email is already in use
    if (error.code === 'auth/email-already-exists') {
      return NextResponse.json({ error: "A user with this email already exists." }, { status: 400 });
    }
    // If the phone number is invalid
    if (error.code === 'auth/invalid-phone-number') {
      return NextResponse.json({ error: "Invalid phone number format. Must include country code." }, { status: 400 });
    }
    return NextResponse.json({ error: `An unexpected error occurred while creating staff: ${error.message || String(error)}` }, { status: 500 });
  }
}
